on:
  workflow_call:
    secrets:
      SERVICE_ACCOUNT_TOKEN:
        description: 'Service account access token to checkout private repositories'
        required: true
    inputs:
      context:
        type: string
        description: 'Context for the docker build'
        required: false
        default: .
      dockerfile:
        type: string
        description: 'Location of the dockerfile to use'
        required: false
        default: ./Dockerfile
      tag:
        type: string
        description: 'Override the docker image tag'
      output-type:
        type: string
        description: 'Output location for the generated docker image'
        required: false
        default: 'none'
      image-name:
        type: string
        description: 'The name of the genereated docker image'
        required: false
        default: ${{ github.repository }}
    outputs:
      id:
        description: "Id of the generated docker image"
        value: ${{ jobs.docker.outputs.id }}
      tag:
        description: "Tag used of the generated docker image"
        value: ${{ jobs.docker.outputs.tag }}

name: Build

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.return.outputs.image }}
      id: ${{ steps.return.outputs.id }}
      tag: ${{ steps.return.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Setup Container Registry
        if: ${{ inputs.output-type == 'package' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Infer Docker Metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ inputs.image-name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,event=branch,enable=${{ startsWith(github.ref,'refs/heads/feature/') || startsWith(github.ref,'refs/heads/hotfix/') }},value={{branch}}
            type=sha,event=branch,enable={{is_default_branch}},prefix=
            type=raw,event=branch,enable={{is_default_branch}},value=latest
            type=raw,enable=${{ inputs.tag != '' }},value=${{ inputs.tag }}
      - name: Building Docker Image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Push Image
        if: inputs.output-type == 'package' && steps.meta.outputs.tags != ''
        run: |
          docker load -i /tmp/image.tar
          IMAGE_NAME = "${{ inputs.image-name }}"
          docker push --all-tags ghcr.io/${IMAGE_NAME,, }
      - name: Fix cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Saving Artifacts
        if: ${{ inputs.output-type == 'artifact' }}
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar
      - name: Returning Outputs
        id: return
        run: |
          echo "::set-output name=id::${{ steps.build.outputs.imageid }}"
          echo "::set-output name=tag::${{ steps.meta.outputs.tags }}"
